### ISSUE TITLE
httpkernel 1.0.2 with laravel framework 5.6 problem

### ISSUE THREAD

**Issue by dimitrikalinin** [php-pm/php-pm-httpkernel#100]
Hi guys, 
we are implementing an application based on laravel framework 5.6. As you can see it has in dependencies symfony stuff of the version ~4.0:
```
"symfony/http-foundation": "~4.0",
"symfony/http-kernel": "~4.0"
```
 the php-pm-httpkernel v1.0.2 has following composer rules:
```
"symfony/http-foundation": "^2.6|^3.0",
"symfony/http-kernel": "^2.6|^3.0"
```
though you have in the v1.0.2 release notes: "Fixed Symfony 4 support and removed StrongerNativeSessionStorage workaround".
what is strange because the php-pm project v1.0.2 is the symfony 4.0 ready:
```
"symfony/console": "^2.6|^3.0|^4.0",
"symfony/debug": "^2.6|^3.0|^4.0",
"symfony/process": "^2.6|^3.0|^4.0"
```
This is fixed in the master branch of the php-pm-httpkernel:
```
"symfony/http-foundation": "^2.6|^3.0|^4",
"symfony/http-kernel": "^2.6|^3.0|^4"
```
but we can not use it on production. Is there a reason why you did it on this way? We would avoid using some unstable versions. What would you recommend to do?

**Comment by andig** [comment]
Omission. Use http-kernel@dev-master as 1.0.2

**Comment by dimitrikalinin** [comment]
Every commit in dev-master can potentially break something. Don't you plan to create a new tag in the near future?

**Comment by andig** [comment]
Will draft a release asap. Apart from the you can use the workaround as suggested.
