### ISSUE TITLE
Composer Depdendency Problem

### ISSUE THREAD

**Issue by aftabnaveed** [php-pm/php-pm-httpkernel#104]
When trying to install the HttpKernel via composer I get dependency errors: 

`composer require php-pm/httpkernel-adapter:dev-master`

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-pm/httpkernel-adapter dev-master requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2] but these conflict with your requirements or minim
um-stability.
    - php-pm/httpkernel-adapter dev-master requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2] but these conflict with your requirements or minim
um-stability.
    - php-pm/httpkernel-adapter dev-master requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2] but these conflict with your requirements or minim
um-stability.
    - Installation request for php-pm/httpkernel-adapter dev-master -> satisfiable by php-pm/httpkernel-adapter[dev-master].
```

**Comment by andig** [comment]
Your problem is that you've requiring dev-master which in turn depends on a stable version. Make sure that you require php-pm/php-pm as well, potentially you'll need a branch alias.

If there's not particular reason you should not use dev versions directly.

**Comment by aftabnaveed** [comment]
Ok I previously cloned the repo and then tried the dev-master and got that error: Now I installed both v1.0  and it worked. 

Thanks

**Comment by aftabnaveed** [comment]
Is there a way to run it on 0.0.0.0:8080 ? 

thanks.

**Comment by aftabnaveed** [comment]
Nevermind I figured it out ppm config  generates ppm.json where you can change the configuration.
