### ISSUE TITLE
Set localhost as a trusted-proxy

### ISSUE THREAD

**Issue by bratao** [php-pm/php-pm-httpkernel#110]
Into my local fork I had to set localhost as a trusted-proxy for Laravel/Symfony

So during a reverse proxy using Nginx I can detect correctly the protocol for asset()

Line 190 on function mapRequest @ HttpKernel.php
`$class::setTrustedProxies(array('127.0.0.1/8'));`

I just created this Issue so others can find a solution. I think that the correct way should set trusted proxies as a config.

**Comment by andig** [comment]
Definitely. We had an older discussion about- this should be a bootstrap-specific config option.

**Comment by mathieudz** [comment]
This is fixed in #114
