### ISSUE TITLE
Unable to install on clean Laravel 5.6 project

### ISSUE THREAD

**Issue by george-kar** [php-pm/php-pm-httpkernel#113]
Following the instructions on the main page I get the response:

  Problem 1
    - Installation request for php-pm/httpkernel-adapter dev-master -> satisfiable by php-pm/httpkernel-adapter[dev-master].
    - php-pm/httpkernel-adapter dev-master requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability.

Is it working on Laravel 5.6 ?

**Comment by andig** [comment]
I've updated the installation instructions in 4ee4570cc60d0a3a5c2e46a438f98dab68cb18fe.

Due to some recent fixes you can- for the time being- also use something like this:

    composer require php-pm/php-pm "php-pm/httpkernel-adapter:dev-master as 1.1"
