### ISSUE TITLE
Monolog BufferHandler does not flush at the end of the request

### ISSUE THREAD

**Issue by dnna** [php-pm/php-pm-httpkernel#134]
This handler flushes using a `register_shutdown_function`, which is never triggered with PPM. We need to find a way to call the `flush()` function of the handler (and maybe any other Monolog handlers that have it?) at the end of the request.

**Comment by andig** [comment]
Interesting finding. Maybe we should look at shutdown functions at the end of each request and invoke all?

**Comment by dnna** [comment]
I'm not sure if its possible to iterate the shutdown functions in PHP code, I don't think they are exposed (closest I found was https://stackoverflow.com/questions/3140257/list-of-registered-shutdown-functions).

I was thinking of handling it on the framework's bootstrap, but then it will have to be handled for each framework separately.

**Comment by andig** [comment]
Should have been fixed by #279
