### ISSUE TITLE
[Laravel] Can not access request data

### ISSUE THREAD

**Issue by tobiasdierich** [php-pm/php-pm-httpkernel#136]
## Description

Access the request data using `$request->get('data')` returns nothing, however using `$request->data` works.

## Setup:

Laravel app running inside the `phppm/nginx` container

php-pm: v1.0.4
php-pm-httpkernel: v1.0.4
Laravel: v5.6

## Steps to reproduce:

1. Clone my example repo: `git clone https://github.com/tobiasdierich/php-pm-example` (The only important bit is here: https://github.com/tobiasdierich/php-pm-example/blob/master/routes/api.php`)
2. Run composer: `composer install --no-dev`
3. Start php-pm: ``docker run -v `pwd`:/var/www -p 8080:80 phppm/nginx --bootstrap=laravel --static-directory=public/``
4. Make a post request to `/api/foo` with POST data:

```json
{
   "foo": "bar"
}
```
5. Make the same request to `/api/bar`

## Result:

The first request to `/api/foo` returns nothing, the second however returns `bar`.

## Expected behaviour:

Both requests should return `bar`.

**Comment by tobiasdierich** [comment]
I did some tinkering and figured out that this could easily be fixed by changing the way how the laravel request instance is created.
 
Instead of directly creating a new `Illuminate\Http\Request` instance, you could create a Symfony request first and convert it to an Illuminate request by using `Illuminate\Http\Request::createFromBase($symfonyRequest)`. This is the way the laravel kernel does it as well.

I'd be happy to contribute a PR to fix this.

**Comment by andig** [comment]
Sounds good, pr and test case would be highly appreciated. 

Viele Grüße,
Andreas

**Comment by dskozin** [comment]
#138
