### ISSUE TITLE
Empty php://input on post request.

### ISSUE THREAD

**Issue by dskozin** [php-pm/php-pm-httpkernel#138]
Hello!
I'm trying to use php-pm, but have empty php://input on post request.
This happens when run in docker and when run without docker.
Can't understand why.

I thought this may because nginx, but i just proxy request from nginx to embeded server, and it's work properly.

Somebody can help me?

May be similar to #136

**Comment by andig** [comment]
Which bootstrap and what type of post request?

Viele Grüße,
Andreas

**Comment by andig** [comment]
Actually, if you're using a request/response framework- why should `php://input` even work at all? IMHO that is a wrong expectation when working with these frameworks. All request properties are exposed via the respective request abstractions.

**Comment by dskozin** [comment]
If request is large there is more useful to use it as stream.
Php://input is a normal way to get post data.

**Comment by andig** [comment]
Ping @dskozin can we close this issue?

**Comment by andig** [comment]
You‘re welcome
