### ISSUE TITLE
httpkernel-adapter/Bootstraps/Laravel.php:165 Exception

### ISSUE THREAD

**Issue by seateng** [php-pm/php-pm-httpkernel#142]
The exception was: ArgumentCountError: ReflectionMethod::__construct() expects exactly 1 parameter, 2 given in /Users/seateng/Projects/Seateng/labs/laravel/laravel_ppm/vendor/php-pm/httpkernel-adapter/Bootstraps/Laravel.php:165

$method = new \ReflectionMethod(get_class($this->app), ['name' => 'register']);
to:
$method = new \ReflectionMethod(get_class($this->app), 'register');

Running!

**Comment by andig** [comment]
I‘m confused- this class has 2 constructors? See http://php.net/manual/en/reflectionmethod.construct.php

**Comment by marcj** [comment]
Yeah, but it does not have `(string, array)`, so we need to call it via `(string, string)`.

**Comment by andig** [comment]
Fair, but that should not cause the error message above? I‘ll give it another try...

**Comment by snellingio** [comment]
I can confirm this is an issue on my end. Will look at making a PR this week. Haven't run into this issue until starting a new project with the latest version of php & Laravel

**Comment by snellingio** [comment]
Already been fixed. Sorry!

**Comment by snellingio** [comment]
If you run into this issue: the current tagged versions do not have this fix. Set `php-pm/httpkernel-adapter` to `dev-master` and you're good to go!
