### ISSUE TITLE
Release SF5 file upload patch as a stable release

### ISSUE THREAD

**Issue by dave-redfern** [php-pm/php-pm-httpkernel#170]
The HttpKernel bridge was patched in #169 to account for the change in UploadedFile signature, but has not been released as a stable update. Right now 2.0.3 is not compatible with SF5.

Could you tag a 2.0.4 that includes this fix?

**Comment by andig** [comment]
Done :)

**Comment by dave-redfern** [comment]
@andig Thank you - much appreciated!
