### ISSUE TITLE
Including autoload assumes working dir = base path

### ISSUE THREAD

**Issue by andig** [php-pm/php-pm-httpkernel#2]
`HttpKernelBridge` does and ugly autoload include relative to the current directory in https://github.com/php-pm/php-pm-httpkernel/blob/master/Bridges/HttpKernel.php#L39:

        require_once './vendor/autoload.php';

This will be wrong if the working directory is different from the base path of the script including the kernel adapter.

I'd rather suggest 

    require_once dirname(realpath($_SERVER['SCRIPT_NAME'])) . '/vendor/autoload.php';

Sounds good?

Alternatively we good assume that the `appBootstrap` itself will be able to the path accordingly. Maybe better make the `require` and optional `include`?

**Comment by marcj** [comment]
If that works correctly within CLI call, then yeah :)
