### ISSUE TITLE
Possible discrepancy in bootstrap.

### ISSUE THREAD

**Issue by suhaibmalik** [php-pm/php-pm-httpkernel#21]
I get the following error when trying to launch with the latest patch:

Declaration of PHPPM\Bridges\HttpKernel::bootstrap($appBootstrap, $appenv, $debug) must be compatible with PHPPM\Bridges\BridgeInterface::bootstrap($appBootstrap, $appenv) in /var/www/beta/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php on line 14.

In BridgeInterface.php of php-pm, there is no $debug argument.

**Comment by suhaibmalik** [comment]
Nevermind my last, this was a problem on my end.

**Comment by marcj** [comment]
Guess php-pm & php-pm-httpkernel was not on the newest master version :)

**Comment by suhaibmalik** [comment]
@marcj That was exactly it. Also, I wasn't running composer install in the php-fpm directory which I now did. However, I now have another error:
...
Starting PHP-PM with 4 workers, using StreamSelectLoop ...
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/beta.laggygamerz.com/bootstrap/app.php:14
...
