### ISSUE TITLE
Can't find Illumnate\Foundation\Application

### ISSUE THREAD

**Issue by suhaibmalik** [php-pm/php-pm-httpkernel#22]
Thanks for the cookie fix. Excited to try it out but I can't just yet. I'm getting the following error with Laravel 5.1.

> Starting PHP-PM with 4 workers, using StreamSelectLoop ...
> PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/beta.laggygamerz.com/bootstrap/app.php:14
> Stack trace:
> #0 /var/www/beta.laggygamerz.com/vendor/php-pm/php-pm/vendor/php-pm/httpkernel-adapter/Bootstraps/Laravel.php(47): require_once()
> #1 /var/www/beta.laggygamerz.com/vendor/php-pm/php-pm/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php(51): PHPPM\Bootstraps\Laravel->getApplication()
> #2 /var/www/beta.laggygamerz.com/vendor/php-pm/php-pm/ProcessSlave.php(125): PHPPM\Bridges\HttpKernel->bootstrap('PHPPM\\Bootstrap...', 'production', false)
> #3 /var/www/beta.laggygamerz.com/vendor/php-pm/php-pm/ProcessSlave.php(57): PHPPM\ProcessSlave->bootstrap('PHPPM\\Bootstrap...', 'production', false)
> #4 /tmp/dbgfFRoNd(6): PHPPM\ProcessSlave->__construct('httpKernel', 'PHPPM\\Bootstrap...', Array)
> #5 {main}
>   thrown in /var/www/beta.laggygamerz.com/bootstrap/app.php on line 14

Any insight?

**Comment by andig** [comment]
Should already be fixed, please retest.

**Comment by suhaibmalik** [comment]
@andig Can confirm! Cookies working too now!

**Comment by marcj** [comment]
awesome :)

**Comment by topcoder108** [comment]
:(
