### ISSUE TITLE
Is it possible to handle streamed responses?

### ISSUE THREAD

**Issue by andig** [php-pm/php-pm-httpkernel#25]
Looking at https://github.com/php-pm/php-pm-httpkernel/blob/master/Bridges/HttpKernel.php#L142 we read the entire response and then send it on via react. Reading en-bloc is a very un-reactish thing to do but I have so far not found and good approach to read the response as its being delivered and pass on to react.

Any ideas?

**Comment by marcj** [comment]
When Symfony has a stream in the streamed response we could wrap it with a React Stream and assign it to HttpResponse (methods tbd) which is then checked and handled as stream in our HttpServer.

**Comment by andig** [comment]
> When Symfony has a stream in the streamed response we could wrap it with a React Stream and assign it to HttpResponse (methods tbd) which is then checked and handled as stream in our HttpServer.

Unfortunately, a `StreamedResponse` simply calls a user function to `echo` it's content: https://github.com/symfony/http-foundation/blob/master/StreamedResponse.php#L78. I didn't find an approach to make this an async process- I guess its not possible with this interface?

**Comment by marcj** [comment]
continue in https://github.com/php-pm/php-pm-httpkernel/issues/36
