### ISSUE TITLE
 undefined method Closure::call()

### ISSUE THREAD

**Issue by klepsydra** [php-pm/php-pm-httpkernel#26]
What is the best version that still works with Symfony 2.8.3 and  PHP 5.5.9?

`./bin/ppm -vvv start  --bridge=HttpKernel --host "0.0.0.0" --port 9090 --workers 1 --app-env "dev" --debug 1 --logging 1 --bootstrap=symfony 
`

I keep getting:

> 
> [21/Mar/2016:11:29:43 +0100] File changed /var/www/clients/client3/web2/src/SystemExt/MainBundle/Classes/EntHelper.php (detection 0.012888, 899). Reload workers.
> Worker closed 5501
> Start new worker 5501
> Worker registered 5501
> PHP Fatal error:  Call to undefined method Closure::call() in /var/www/clients/client3/web2/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php on line 80
> PHP Stack trace:
> PHP   1. {main}() /tmp/dbgwtZKqK:0
> PHP   2. PHPPM\ProcessSlave->__construct() /tmp/dbgwtZKqK:13
> PHP   3. React\EventLoop\StreamSelectLoop->run() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:67
> PHP   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:201
> PHP   5. call_user_func() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:232
> PHP   6. React\Socket\Connection->handleData() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:232
> PHP   7. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/react/socket/src/Connection.php:15
> PHP   8. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP   9. React\Http\RequestParser->feed() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  10. React\Http\RequestParser->finishParsing() /var/www/clients/client3/web2/vendor/react/http/src/RequestParser.php:50
> PHP  11. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/react/http/src/RequestParser.php:86
> PHP  12. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  13. PHPPM\React\HttpServer->PHPPM\React\{closure}() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  14. PHPPM\React\HttpServer->handleRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/React/HttpServer.php:38
> PHP  15. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/php-pm/php-pm/React/HttpServer.php:72
> PHP  16. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  17. PHPPM\ProcessSlave->onRequest() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  18. PHPPM\ProcessSlave->handleRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:208
> PHP  19. PHPPM\Bridges\HttpKernel->onRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:226
> PHP  20. PHPPM\Bootstraps\Symfony->preHandle() /var/www/clients/client3/web2/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php:83
> PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\UndefinedMethodException' with message 'Attempted to call an undefined method named "call" of class "Closure".' in /var/www/clients/client3/web2/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php:80
> Stack trace:
> #0 /var/www/clients/client3/web2/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php(83): PHPPM\Bootstraps\Symfony->preHandle()
> #1 /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php(226): PHPPM\Bridges\HttpKernel->onRequest()
> #2 /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php(208): PHPPM\ProcessSlave->handleRequest()
> #3 /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): PHPPM\ProcessSlave->onRequest()
> #4 /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array()
> #5 /var/www/clients/client3/web2/vendor/php-pm/php-pm/React/HttpServer.php(72): Evenement\EventEmitter->emit()
> #6 /var/www/clients/clien in /var/www/clients/client3/web2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php on line 90
> PHP Stack trace:
> PHP   1. {main}() /tmp/dbgwtZKqK:0
> PHP   2. PHPPM\ProcessSlave->__construct() /tmp/dbgwtZKqK:13
> PHP   3. React\EventLoop\StreamSelectLoop->run() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:67
> PHP   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:201
> PHP   5. call_user_func() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:232
> PHP   6. React\Socket\Connection->handleData() /var/www/clients/client3/web2/vendor/react/event-loop/src/StreamSelectLoop.php:232
> PHP   7. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/react/socket/src/Connection.php:15
> PHP   8. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP   9. React\Http\RequestParser->feed() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  10. React\Http\RequestParser->finishParsing() /var/www/clients/client3/web2/vendor/react/http/src/RequestParser.php:50
> PHP  11. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/react/http/src/RequestParser.php:86
> PHP  12. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  13. PHPPM\React\HttpServer->PHPPM\React\{closure}() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  14. PHPPM\React\HttpServer->handleRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/React/HttpServer.php:38
> PHP  15. Evenement\EventEmitter->emit() /var/www/clients/client3/web2/vendor/php-pm/php-pm/React/HttpServer.php:72
> PHP  16. call_user_func_array() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  17. PHPPM\ProcessSlave->onRequest() /var/www/clients/client3/web2/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
> PHP  18. PHPPM\ProcessSlave->handleRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:208
> PHP  19. PHPPM\Bridges\HttpKernel->onRequest() /var/www/clients/client3/web2/vendor/php-pm/php-pm/ProcessSlave.php:226
> PHP  20. PHPPM\Bootstraps\Symfony->preHandle() /var/www/clients/client3/web2/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php:83
> Status: 500 Internal Server Error
> X-Powered-By: PHP/5.5.9-1ubuntu4.14
> Set-Cookie: PHPSESSID=420c8e75avnp0brf2dbe22a081; path=/; HttpOnly
> Content-type: text/html
> 
>

**Comment by andig** [comment]
Outch. `Closure::call` is only available as of PHP7. ping @marcj

**Comment by andig** [comment]
Please test if this works.

**Comment by klepsydra** [comment]
Confirmed fixed, thanks for the rapid response!

Now it loads further into an older issue, but unrelated to this, and probably more to do with my project:
 

> 
> Filter 'softdeleteable' is not enabled.
> 500 Internal Server Error - InvalidArgumentException
> 
> Stack Trace
> in vendor/doctrine/orm/lib/Doctrine/ORM/Query/FilterCollection.php at line 159   -
> 
> 
http://strat.sqr-dev.pl:9090/
