### ISSUE TITLE
Symfony bridge no longer supports HttpKernel applications

### ISSUE THREAD

**Issue by andig** [php-pm/php-pm-httpkernel#28]
Before the major rework, the Symfony bridge was actually an HttpKernel bridge with some added support Symfony support. Right now it is Symfony applications only and doesn't support simple HttpKernal applications anymore:

	$ if [ -n "$DB" ]; then phpunit $TRAVIS_TEST_EXCLUDES,aggregation; fi
	/home/travis/build/andig/volkszaehler.org
	+---------------------+--------------------------+
	| bridge              | HttpKernel               |
	| host                | 127.0.0.1                |
	| port                | 8080                     |
	| workers             | 8                        |
	| app-env             | dev                      |
	| debug               | 1                        |
	| logging             | 1                        |
	| bootstrap           | PHPPM\Bootstraps\Symfony |
	| max-requests        | 1000                     |
	| concurrent-requests |                          |
	| php-cgi             |                          |
	+---------------------+--------------------------+
	Starting PHP-PM with 8 workers, using StreamSelectLoop ...
	--- Worker 5507 stderr ---
	PHP Fatal error:  Class 'AppKernel' not found in /home/travis/build/andig/volkszaehler.org/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php on line 54
	--- Worker 5502 stderr ---
	PHP Fatal error:  Class 'AppKernel' not found in /home/travis/build/andig/volkszaehler.org/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php on line 54
	--- Worker 5507 stderr ---
	PHP Stack trace:
	PHP   1. {main}() /tmp/dbgQIcWrs:0
	PHP   2. PHPPM\ProcessSlave->__construct() /tmp/dbgQIcWrs:13
	PHP   3. PHPPM\ProcessSlave->run() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessSlave.php:89
	PHP   4. React\EventLoop\StreamSelectLoop->run() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessSlave.php:250
	PHP   5. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /home/travis/build/andig/volkszaehler.org/vendor/react/event-loop/src/StreamSelectLoop.php:201
	PHP   6. call_user_func:{/home/travis/build/andig/volkszaehler.org/vendor/react/event-loop/src/StreamSelectLoop.php:232}() /home/travis/build/andig/volkszaehler.org/vendor/react/event-loop/src/StreamSelectLoop.php:232
	PHP   7. React\Socket\Connection->handleData() /home/travis/build/andig/volkszaehler.org/vendor/react/event-loop/src/StreamSelectLoop.php:232
	PHP   8. Evenement\EventEmitter->emit() /home/travis/build/andig/volkszaehler.org/vendor/react/socket/src/Connection.php:15
	PHP   9. call_user_func_array:{/home/travis/build/andig/volkszaehler.org/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /home/travis/build/andig/volkszaehler.org/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
	PHP  10. PHPPM\ProcessSlave->PHPPM\{closure}() /home/travis/build/andig/volkszaehler.org/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
	PHP  11. PHPPM\ProcessSlave->processMessage() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessCommunicationTrait.php:50
	PHP  12. PHPPM\ProcessSlave->commandBootstrap() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessCommunicationTrait.php:26
	PHP  13. PHPPM\ProcessSlave->bootstrap() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessSlave.php:255
	PHP  14. PHPPM\Bridges\HttpKernel->bootstrap() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/php-pm/ProcessSlave.php:174
	PHP  15. PHPPM\Bootstraps\Symfony->getApplication() /home/travis/build/andig/volkszaehler.org/vendor/php-pm/httpkernel-adapter/Bridges/HttpKernel.php:50

**Comment by marcj** [comment]
Has this been fixed? :) I tried also Laravel, which worked.
