### ISSUE TITLE
Can we expect a Silex bootstrap?

### ISSUE THREAD

**Issue by bouiboui** [php-pm/php-pm-httpkernel#38]
I tried ppm on a project of mine thinking it would be compatible since Silex and Symfony share a lot... It does not. Do you plan on supporting Silex anytime in the future?

**Comment by jbenoit2011** [comment]
I'm currently working on a bootstrap for Silex, here is the first draft:

```
<?php

namespace PHPPM\Bootstraps;

use PHPPM\Bootstraps\BootstrapInterface;
use Silex\Application;

class Silex implements BootstrapInterface
{
    /**
     * @var string
     */
    private $appEnv;

    /**
     * @var bool
     */
    private $debug;

    /**
     * @param $appenv
     * @param $debug
     */
    public function __construct($appenv, $debug)
    {
        $this->appEnv = $appenv;
        $this->debug = $debug;
    }

    /**
     * @return Application
     */
    public function getApplication()
    {
        $app = require './src/app.php';
        require './config/prod.php';
        require './src/controllers.php';

        return $app;
    }

    /**
     * @return string
     */
    public function getStaticDirectory()
    {
        return './web';
    }
}
```
Works with a new Silex Skeleton:
```
composer create-project fabpot/silex-skeleton /var/www/helloworld && \
cd /var/www/helloworld && \
composer config minimum-stability dev && \
composer require php-pm/httpkernel-adapter:dev-master && \
composer require php-pm/php-pm:dev-master
```
Then copy the bootstrap file into `/var/www/helloworld/vendor/php-pm/httpkernel-adapter/Bootstraps/Silex.php`

Dump your autoloader to make sure the class you copy is taken in account:
`composer dumpautoload`

Finally launch the app with: `./vendor/bin/ppm start --bootstrap=silex`

If I produce a better version, I will do a PR.

**Comment by bouiboui** [comment]
That's awesome, hopefully I can try it soon

**Comment by dave08** [comment]
@jbenoit2011 Is what you proposed stable for production? Are you still working on this? Also would this be compatible with Silex 1.~? Thanks!!

**Comment by jbenoit2011** [comment]
The code I pasted above ran in production on an app handling thousands of requests per day built with Silex 2.x while several months with no issues. But I did not test it with Silex 1.x.

**Comment by andig** [comment]
@jbenoit2011 would you care to submit a PR?

**Comment by andig** [comment]
Closing due to missing feedback. Silex is meanwhile deprecated as well.

**Comment by charly22** [comment]
@andig what do you mean with Silex is being deprecated? 

Besides that, what kind of feedback do you need to keep this issue open?

**Comment by alsar** [comment]
Silex is not developed anymore. It was deprecated a few weeks ago.
http://symfony.com/blog/the-end-of-silex

**Comment by charly22** [comment]
@alsar thanks for the notice.
