### ISSUE TITLE
bridge to symfony and php-sgi

### ISSUE THREAD

**Issue by trim-fly** [php-pm/php-pm-httpkernel#4]
Is it possible to use/combine this project with uWSGI server with php-sgi ( https://github.com/unbit/uwsgi-phpsgi/ ) plugin? 
i think it should be great to use stable and super-fast uWSGI server and symfony2 as application.

**Comment by andig** [comment]
From https://github.com/unbit/uwsgi-phpsgi/: 

> will load app.php from the current directory and will execute its 'application' function at every request

The whole point with php-pm is that you do NOT need to load the php scripts on each request. Or am I missing something?

**Comment by trim-fly** [comment]
yes. main point of 'php-sgi' plugin is to make application load all environment/classes/etc just once (same as php-pm project), and then on each request it will call only one entry-point function (currently hardcoded to "application" but will be manageable on release). it is just like infinite loop around "application" function.
so, i think this project (httpkernel bridge) can be adjusted somehow to load all symfony components and then just provide "application" function to actually do the job on request.
i am sysadmin, not a programmer, so maybe i'm wrong and my request is a nonsence.

**Comment by andig** [comment]
Both projects are apparently doing the same thing- load stuff once. I don't see why we would wish to modify this one to provide functionality to the other to achieve the same result we already have? Wontfix imho.

**Comment by marcj** [comment]
I don't get your point either @trim-fly
