### ISSUE TITLE
Laravel headers

### ISSUE THREAD

**Issue by uniring** [php-pm/php-pm-httpkernel#41]
We've seen that request headers persist through different requests. For example, we're sending the Authentication header from one browser and getting an authenticated response from another without providing the header (we are using php-pm with only one worker to test this).

We're using Laravel 5.2 with Dingo.

Any help to fix this would be appreciated.

Thanks,

**Comment by duxet** [comment]
I have fixed this issue in PR #39 - but there still might be some bugs, as Laravel contains a lot of global and static things, that doesn't play well with such architecture.

**Comment by OSDDQD** [comment]
@duxet thankts, workы well, continue to testing.

**Comment by andig** [comment]
I've meanwhile ported my app to JWT and will try to verify this.

**Comment by dzubchik** [comment]
This  https://github.com/php-pm/php-pm/commit/9b63b997f6cb1b5cfec650d22c46a99256eadbcd should fix an issue.

**Comment by andig** [comment]
Closing due do missing feedback. Please feel free to reopen.
