### ISSUE TITLE
Cookie expire time incorrect (Laravel 5.2)

### ISSUE THREAD

**Issue by isopropil** [php-pm/php-pm-httpkernel#42]
Trying to use with Laravel 5.2. 
When Laravel set a cookie (session and csrf token), the expiration time of this cookies is in past. 
Standart Laravel cookie lifetime - 2 hours, but I receive a cookie, that expired a hour ago. My current timezone - +0300. What happens?
Thank you.

**Comment by andig** [comment]
Does the same setup work when you're serving via apache/nginx instead of php-pm?

**Comment by marcj** [comment]
looks like your timesettings are wrong. php-pm doesnt do anything special with cookies lifetime.

**Comment by isopropil** [comment]
With nginx+php-fpm all works properly. Time settings also correct.

**Comment by isopropil** [comment]
httpkernel-adapter modifying cookie lifetime. 
Bridges/HttpKernel.php, line 223. Simply change gmdate to date.

**Comment by andig** [comment]
@isopropil 

> httpkernel-adapter modifying cookie lifetime. Bridges/HttpKernel.php, line 223. Simply change gmdate to date.

According to http://stackoverflow.com/questions/21120882/the-date-time-format-used-in-http-headers it needs be GMT. So- where do we go wrong here? I also don't see why- if its wrong- this would differ from nginx and apache?

**Comment by isopropil** [comment]
This describes only date format. But gmdate() returns a Greenwich time (time from "0" timezone). 
Example:
        echo date('D, d-M-Y H:i:s', time()). ' GMT'; // Tue, 19-Jul-2016 10:34:53 GMT
        echo gmdate('D, d-M-Y H:i:s', time()). ' GMT'; // Tue, 19-Jul-2016 07:34:53 GMT
Also, Laravel with php-fpm and nginx set correct dates in cookies.

**Comment by andig** [comment]
Could you push a small PR?

**Comment by marcj** [comment]
> All HTTP date/time stamps MUST be represented in Greenwich Mean Time (GMT), without exception.

So, seems to me, we're doing right. Is your timezone correctly set in php.ini (not of fpm/,cli/, but from cgi/ folder)?

gmdate doesn't return from 0 timezone, but from your set timezone. If this is wrong, gmdate will return wrong results. Since on ubuntu fpm/cgi/cli have different php.ini files chances are high you have just put your server-timezone into the wrong php.ini.

**Comment by marcj** [comment]
To make it more clear, on my ubuntu for example `/etc/php/7.0/cgi/php.ini` needs to have `date.timezone = UTC` if your server timezine (see `date` command) is UTC (which is highly recommended).

**Comment by andig** [comment]
ping @isopropil is this still an issue?

**Comment by andig** [comment]
Closing due to missing feedback
