### ISSUE TITLE
In Symfony, if first call is https, all routes to http get a :0, breaking routes

### ISSUE THREAD

**Issue by ConneXNL** [php-pm/php-pm-httpkernel#43]
I am testing PHP-PM with Symfony Framework, however I got into a problem with the Symfony Router. Whenever the first page loaded via PHP-PM is a HTTPS call, all routes to http pages will have a ":0" port at the end. For example, links on https://www.example.com/user-dashboard will create links to http pages that look like: http://www.example.com:0/.

I tried to find out why this was happening and apparently the Symfony\Component\Routing\RequestContext  has a property called $httpPort that somehow is set to 0 instead of the default 80 if the first call is a HTTPs call.

I patched this in an ugly way in the Symfony.php by adding the following 2 lines:

```
        $app->handle($request);

        if ($app->getContainer()->has('router.request_context'))
            $app->getContainer()->get('router.request_context')->setHttpPort(80);
        
        $this->postHandle($app);

```

I am not sure what the correct way to handle this problem is, nor do I know why it becomes a "0" in the first place (whereas normally that doesn't happen in Symfony).

**Comment by andig** [comment]
Are you running php-pm behind a reverse proxy for the https use case? What's your setup?

**Comment by ConneXNL** [comment]
I am running on nginx

```
upstream backend  {
    server 127.0.0.1:8000 max_fails=1 fail_timeout=5s;
}

    location @phppm {
        proxy_pass http://backend;
        proxy_next_upstream http_502 timeout error;
        proxy_connect_timeout 1;
        proxy_send_timeout 5;
        proxy_read_timeout 5;

        proxy_intercept_errors on;
        recursive_error_pages on;

        error_page 400 = @symfony;
        error_page 500 = @symfony;
        error_page 501 = @symfony;
        error_page 502 = @symfony;
        error_page 503 = @symfony;
        error_page 504 = @symfony;


        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

```

**Comment by marcj** [comment]
Where is `@symfony` defined?

**Comment by andig** [comment]
Closing due to missing feedback.
