### ISSUE TITLE
Wrong headers

### ISSUE THREAD

**Issue by dzubchik** [php-pm/php-pm-httpkernel#47]
Hi! We have recently megred #46, but unfortunately, it brings a bug. When we call "add" method
https://github.com/php-pm/php-pm-httpkernel/blob/master/Bridges/HttpKernel.php#L183, we add headers from React request, but we can not track headers which were added by Symfony request from ServerBag. As it uses superglobal array $_SERVER, which only grows during application lifetime. For example:
I send regular http request, after that I send ajax request, all furtherst requests will have X-Request-With: XMLHttpRequest header. My propose is to return replace method, but move authorization headers from $_SERVER to $headers.

**Comment by marcj** [comment]
How about resetting $_SERVER at the beginning of the method?

**Comment by dzubchik** [comment]
I don't think that resetting superglobal is ok. And, furthermore, Symfony ServerBag uses it to populate headers.

**Comment by marcj** [comment]
Yes, this is an issue, because $_SERVER should contain always only headers from the $request, not from the first php bootstrap. We need to reset it anyways.

**Comment by dzubchik** [comment]
This commit fixes this https://github.com/php-pm/php-pm/commit/9b63b997f6cb1b5cfec650d22c46a99256eadbcd.
