### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by kelunik** [php-pm/php-pm-httpkernel#59]
There should be a tagged release, maybe `v0.1.0`.

**Comment by marcj** [comment]
Why? We do not have any official API yet. Every release would be horrible breaking.

**Comment by kelunik** [comment]
Which is totally fine, just release `v0.2.0` next. `dev-master` requires pinning specific commits and doesn't allow for minor / bugfix releases, that are easily applied.

**Comment by marcj** [comment]
There literally no advantage of using semantic versions when you have no semantic behind it and a random git commit-id like you'd get when you use `dev-master` has basically the same meaning.

**Comment by kelunik** [comment]
See #58 for issues with commit pinning. It might not be that relevant, as this package should only be required by apps, not libraries, but who knows.

**Comment by andig** [comment]
We are aware of these issues. At this time its the only solution while we're waiting for react/http.

**Comment by andig** [comment]
Closing in favour of https://github.com/php-pm/php-pm/issues/297. This issue tracks roadmap until rel. 1.0.
