### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by kelunik** [php-pm/php-pm-httpkernel#67]
Please add a `LICENSE` file and add the license to `composer.json`.

**Comment by andig** [comment]
I'd propose to add the license of php-pm, which is MIT

**Comment by andig** [comment]
@kelunik would you mind doing a PR for MIT? I'd assume this repo is part of ppm and therefore MIT undebatable.

**Comment by kelunik** [comment]
I guess technically you have to ask all contributors whether they're fine with that.

**Comment by marcj** [comment]
php-pm-httpkernel is a central component of php-pm, latter is MIT and we reference to it in README. We just add the MIT license, if someone of the contributors (@yuloh, @Matthimatiker, @branchzero, @dzubchik, @frag-seb, @petk, @maciejmrozinski) want to remove their code or want to suit me, my address is here marcjschmidt.de.

**Comment by marcj** [comment]
Added it, but we could also add it to `composer.json`.
