### ISSUE TITLE
Class 'Symfony\Component\ClassLoader\ClassCollectionLoader' not found

### ISSUE THREAD

**Issue by skedone** [php-pm/php-pm-httpkernel#7]
Cloned the repository php-pm.
I required the httpKernel interface but, when I try to load a new sf2.7 installation, it doesn't work.

    root@billow:/var/opt/php-pm# ./bin/ppm start --workers 1 /var/opt/hashmag/ --bridge=httpKernel -vvv
    1 slaves (5501) up and ready.
    PHP Fatal error:  Class 'Symfony\Component\ClassLoader\ClassCollectionLoader' not found in /var/opt/php-pm/vendor/symfony/http-kernel/Kernel.php on line 443
    Boot 1 new slaves ... 1 slaves (5501) up and ready.

Am I missing something? Thanks!

**Comment by andig** [comment]
Mhhm. ClassLoader is only require-dev in Symfony 2.7. Sounds like a Symfony issue to me?

**Comment by skedone** [comment]
If I start the internal webserver in Symfony2 or use NGINX + PHP-FPM, everything is ok.
I am trying to investigate.

**Comment by andig** [comment]
You could check what/why `loadClassCache` at https://github.com/symfony/HttpKernel/blob/2.7/Kernel.php#L387 is being called in the one instance but not the other.

**Comment by skedone** [comment]
Symfony issue, thanks! ;)
