### ISSUE TITLE
Symfony default  logger method missing (SF 4, probably 3.4 also)

### ISSUE THREAD

**Issue by mleczakm** [php-pm/php-pm-httpkernel#81]
`Error: Call to undefined method Symfony\Component\HttpKernel\Log\Logger::getDebugLogger() in /ppm/vendor/php-pm/httpkernel-adapter/Bootstraps/Symfony.php:173` says everything :) Ran from custom dockerfile based on `phppm/nginx` with command `--debug=0 --app-env=dev --static-directory=public/ --bootstrap=Symfony --bridge=HttpKernel`, When I've added missing method (even if it was empty) app works.

Also, with `--debug=1` I still have error `Fatal Error: Cannot declare interface Psr\Log\LoggerInterface, because the name is already in use`.

**Comment by jeromemacias** [comment]
To avoid `Fatal Error: Cannot declare interface Psr\Log\LoggerInterface, because the name is already in use` error, you need to `rm -rf cache/*` and start `php-pm` right after.

**Comment by andig** [comment]
@mleczakm would be interesting which logger you're using. Afaiks the monolog bridge should have the method that fails for you, see https://github.com/symfony/monolog-bridge/blob/4.0/Logger.php

Could you also try duck typing to check which class the container's logger is and if it has the method in question?

**Comment by mleczakm** [comment]
It is `Symfony\Component\HttpKernel\Log`. There is no longer need to use monolog in dev environment.

**Comment by andig** [comment]
I see. Since `Symfony\Component\HttpKernel\Log\Logger` writes to `STDERR` there's nothing to reset in this case. We should just check if the logger implements `DebugLoggerInterface` and only reset in that case.

Would you mind doing a PR?

**Comment by andig** [comment]
Closed via #88
