### ISSUE TITLE
[Symfony] Unexpected behaviors with Doctrine

### ISSUE THREAD

**Issue by benjaminjonard** [php-pm/php-pm-httpkernel#90]
Hello, while using ppm in a Symfony project I encountered some unexpected behaviors with Doctrine.
For example : 

1.  I go on a page with a list of 3 items
2.  Then I go on a page with a form for adding a new item. Everything works fine, the item is inserted in the database
3. But when I go back to the list of items, there is still 3 items instead of 4

I'm not entirely sure of what happens here but Doctrine seems to be using some cached results.
The solution I found is clearing the entity manager at the end of every request.

Should this clearing be added by default to ppm-httpkernel ? Or is there another way to avoid this problem ?

**Comment by andig** [comment]
You'll need to make sure that the caches (query cache? hydration cache?) or UOW are reset. Also- in case your entity manager errors- you'll need to recreate the entity manager at the beginning of the request.

**Comment by benjaminjonard** [comment]
Yes that's what I'm doing ($em->clear() seems to be enough to resolve the problem). 

But I'm wondering if this clearing should be included in ppm-httpkernel because I've reproduced this problem with a new project, so it may concern anyone using Doctrine.

**Comment by andig** [comment]
> But I'm wondering if this clearing should be included in ppm-httpkernel

Definitely not. Your application needs to be able to handle multiple requests which it isn't.

**Comment by zmitic** [comment]
@benjaminjonard Glad you solved it, it took me also some time to figure the problem. But you will encounter few more, take a look at this issue: https://github.com/symfony/symfony/issues/23984

It is pretty easy fix though.

Another problem; long running process will keep DB connection open. When your DB connection closes after some time, Doctrine will throw exception and not try to reopen it.

The only solution is to either allow infinite time for connection or register ``kernel.exception`` event that will do a simple ``die()``. I don't know why, but it just works, php-pm will restart that process. End-user will never notice something happened.

**Comment by andig** [comment]
Seems like this issue has been resolved- closing.
