### ISSUE TITLE
Laravel : Class 'PHPPM\Bridges\HttpKernel' not found

### ISSUE THREAD

**Issue by neoteknic** [php-pm/php-pm-httpkernel#91]
After install I try to run (without docker) : 

ppm start --bootstrap=laravel --app-env=prod --logging=0 --debug=0 --workers=10 --static-directory=public/

But error loop.
there isn't any good tutorial to use php-pm for a laravel app so I may have missing something.

**Comment by andig** [comment]
Did you require php-pm/httpkernel-adapter?

**Comment by andig** [comment]
The error loop is a knoen bug.

**Comment by neoteknic** [comment]
Yes this is my composer :
 "require": {
        "php": ">=7.0.0",
        "barryvdh/laravel-debugbar": "2.*",
        "barryvdh/laravel-ide-helper": "2.*",
        "cboden/ratchet": "^0.4",
        "doctrine/dbal": "^2.5",
        "guzzlehttp/guzzle": "~6.0",
        "intervention/image": "^2.3",
        "jeroendesloovere/vcard": "^1.4",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "lasserafn/php-initial-avatar-generator": "^2.0",
        "mistic100/randomcolor": "1.*",
        "ovh/ovh": "^2.0",
        "php-pm/httpkernel-adapter": "dev-master",
        "spatie/browsershot": "^1.6",
        "textalk/websocket": "1.*"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },

**Comment by neoteknic** [comment]
Php pm was installed in /root, I installed it /home/localhost/php-pm, same problem (I don't know where I have to install it).
I'm on gentoo (compiled fpm+cgi + cli (no apache), + pecl event enabled on cli/cgi)
I did everything in the last block here :
https://github.com/php-pm/php-pm/wiki/Use-without-Docker

The app is curently running on Apache + php-fpm 7.2 + mariadb 10.2 + memcached. I Use port 8180 in config (8080 already used).

**Comment by andig** [comment]
Php-pm and httpkernel need be installed togehter- in your composer they‘re separated. 

Viele Grüße,
Andreas

**Comment by neoteknic** [comment]
I have php-pm because httpkernel-adapter require :
"require": {
        "php-pm/php-pm": "^1.0",$
...
}
so it's useless to require it ? if I require it, same problem.

**Comment by neoteknic** [comment]
With "php-pm/php-pm":"dev-master", in composer there is an error :
php-pm/httpkernel-adapter dev-master requires php-pm/php-pm ^1.0 -> satisfiable by php-pm/php-pm[1.0, 1.0.1] but these conflict with your requirements or minimum-stability.

because httpkernel-adapter require "php-pm/php-pm": "^1.0" readme is wrong ?

**Comment by neoteknic** [comment]
It's working if I install ppm in the same project. And start it with  : 
vendor/php-pm/php-pm/bin/ppm start --bootstrap=laravel --app-env=prod --logging=0 --debug=0 --workers=10 --static-directory=public/


But only the homepage is working, all static res or other pages aren't working : 

string(5252) "ErrorException: Event::add(): Epoll ADD(1) on fd 21 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Operation not permitted in /home/bwaserver/www/vendor/react/event-loop/src/ExtEventLoop.php:258 

I use an apache proxy to have a url without port.
php-pm really need more documentation.

**Comment by neoteknic** [comment]
I close this issue, and reopen anothe one.
php-pm php-pm-httpkernel don't have documentation

**Comment by marcj** [comment]
That looks more like a ReactPHP issue. Please try t uninstall extevent
