### ISSUE TITLE
New session handling requires PHP >=7.1

### ISSUE THREAD

**Issue by Khartir** [php-pm/php-pm-httpkernel#93]
The new session handling as of Version 1.0.2 sets the session id to an empty string. In PHP 7.0 (and maybe lower) this causes `session_start()` to fail with `Warning: session_start(): Cannot start session with empty session ID`.
It works in PHP 7.1 and 7.2 but I'm unsure why. I checked the PHP release notes and could not find a related entry.
The composer.json should require PHP 7.1 or higher.

**Comment by marcj** [comment]
> The composer.json should require PHP 7.1 or higher.

👍

**Comment by andig** [comment]
We're currently supporting 5.6 so the fix is invalid until 2.0 is released. Plus- I know I'm sounding like a broken record- 7.1 would break ppm on Raspbian.

**Comment by marcj** [comment]
Sure, will be 2.0 then

**Comment by andig** [comment]
@marcj haven't we broken php 7.0 support then?

**Comment by marcj** [comment]
Mh, seems like we broke < 7.0 due to that session handling. Actually, all that session handling in a long running process is a PITA in PHP. Would love not to touch it anymore and just say that session handling isn't working for PHP < 7.0. WDYT?

**Comment by Khartir** [comment]
@marcj Just to clarify 7.0 is also broken so it would be < 7.1. Unless PHP 7.0 has been patched and this is now working, I haven't tested it since I created the issue.

**Comment by andig** [comment]
^7.1 is the required version for php-pm.
