### ISSUE TITLE
Support Drupal built with Composer.

### ISSUE THREAD

**Issue by mglaman** [php-pm/php-pm-httpkernel#95]
In `getApplication()` for the Drupal boostrap class it assumes Drupal was not built with Composer.

It needs to be changed to something like

```
        //load drupals autoload.php, so their classes are available
        if (file_exists('./vendor/autoload.php')) {
            $autoloader = require './vendor/autoload.php';
        } else {
            $autoloader = require '../vendor/autoload.php';
        }
```

**Comment by andig** [comment]
> In getApplication() for the Drupal boostrap class it assumes Drupal was not built with Composer.

I don't understand. Both cases above depend on composer. Do you want to explain and file a PR?

**Comment by mglaman** [comment]
Sorry, I should have explained. There are two methods.

1. Download Drupal, composer install.
2. Manage Drupal via Composer using something like https://github.com/drupal-composer/drupal-project

This installs Drupal core via a subtree and puts Drupal in a `web` or `docroot` etc directory. Which means `vendor` is no longer in the same directory as Drupal.
