### ISSUE TITLE
Install with symfony 4

### ISSUE THREAD

**Issue by andreybolonin** [php-pm/php-pm-httpkernel#97]
<img width="1241" alt="screen shot 2018-03-22 at 2 24 59 pm" src="https://user-images.githubusercontent.com/2576509/37770404-fb2c2dca-2ddc-11e8-8b3f-1153a01939cd.png">

**Comment by andig** [comment]
Not a ppm problem but one of composer version constraints.

**Comment by andig** [comment]
> we fixed the compatibility with sf4, but we will not use it +1 :D

No. Just use composer as intended for such situations as suggested:

    composer require "php-pm/php-pm:dev-master as 1.2"
